spring.application.name=supportflow-api


spring.datasource.url=jdbc:postgresql://localhost:5432/supportflow
spring.datasource.username=postgres
spring.datasource.password=postgress


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=8d2e6f9c4a1b7e3f5d8c9a2e6f7b1c3d8e5f9a2b6c7d1e4f8a9b3c5d7e1f2a6
jwt.expiration=86400000


server.port=8080